# Site settings
title: Green View Tea Industries
email: gvtimail@gmail.com
description: "Green View Tea Industries."
baseurl: ""
url: "http://greenviewtea.com"
twitter_username: greenviewtea
github_username:  dhilipsiva

# Build settings
markdown: kramdown
permalink: pretty

assets:
  compress:
    css: sass
    js: uglifier

exclude:
  - "Rakefile"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "config.rb"
  - "README.md"
  - "publish.sh"
  - "serve.sh"
  - "uncss.js"
  - "package.json"
  - "node_modules"
