# Site settings
title: Green View Tea Industries
email: gvtimail@gmail.com
description: "Green View Tea Industries."
baseurl: ""
url: "http://greenviewtea.com"
twitter_username: greenviewtea
github_username:  dhilipsiva

# Build settings
markdown: kramdown
permalink: pretty
